version: '3.7'

services:
  
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - 9010:9010
      - 9020:9020
    networks:
      - game_api_network

  redis:
    image: redis:6
    ports:
      - 6379:6379
      - 6378:6378
    networks:
      - game_api_network

networks:
  game_api_network:
    name: game_api_network
